= Changelog

== Version 2.5.1

* Ignore `Set-Cookie` header of responses in the `deploy` goal

== Version 2.5.0

* Make `chartRepoUrl` optional
* Add logging for property resolution
* Limit property substitution in `package` mojo to the file extensions "json", "tpl", "yml" and "yaml"
* Allow multiple property substitutions on a single line

== Version 2.4.1

* Fix a bug where `chartVersion` always had to be configured explicitly. After this fix, `chartVersion` correctly falls
  back to `project.model.version` again.

== Version 2.4.0

* Support other chart registries like JFrog Artifactory by introducing new optional configuration parameters:
** `chartPublishUrl`
** `chartPublishMethod`
** `chartDeleteUrl`
* Support chart registries that need authentication for pulling images.
* Fix a problem with quoted file path arguments on Linux by only quoting paths that contain a space.

== Version 2.3.0

* Support overriding the chart version using the configuration parameter `chartVersion`. If `chartVersion` is not
  configured, the value for `project.model.version` will be used instead.
* Add support for Helm 3.

== Version 2.2.0

* Update dependency on `jackson-databind` to version 2.9.10 because of
  https://nvd.nist.gov/vuln/detail/CVE-2019-14540[CVE-2019-14540] and
  https://nvd.nist.gov/vuln/detail/CVE-2019-16335[CVE-2019-16335].
* Replace gitflow plugin `jgitflow-maven-plugin` with
  https://github.com/aleksandr-m/gitflow-maven-plugin[gitflow-maven-plugin].

== Version 2.1.1

* Update dependency on `jackson-databind` to version 2.9.9 because of
  https://nvd.nist.gov/vuln/detail/CVE-2019-12086[CVE-2019-12086].

== Version 2.1.0

* Add new goal lint, which runs linting using helm lint.
* Make sure `target/test-classes` is created if it's missing.

== Version 2.0.0

* Support multiple platforms.
* Download official helm binary release if release is missing in remote artifact repository.
* Resolve helm binary as a regular Maven artifact. This allows to share the binary via the local Maven repository,
  so it doesn't have to be re-downloaded for every project.
* Add new goal `template`, which renders the template using `helm template`.
* Set helm chart version via `--version`. This allows to entirely omit the version in the `Chart.yaml`.
* Simplify goal names. Goals now can be run using short names (`mvn helm:package helm:deploy`).
* Do not create files in the temporary system folder any more.
* Introduced `helm.skip` property for skipping plugin execution.
* Packaging and deploying have been split, so you have to add `<goal>deploy</goal>` to the `<goals>` section of the
  plugin configuration. Also, the `<skipPublishing>` option has been removed, since the same result can be achieved by
  omitting the `deploy` goal from the `<goals>`.
