= Usage

Add the following to your `pom.xml`

....
<build>
  <plugins>
    ...
    <plugin>
      <groupId>com.deviceinsight.helm</groupId>
      <artifactId>helm-deploy-maven-plugin</artifactId>
      <version>1.16</version>
      <configuration>
        <chartName>sth-project</chartName>
        <chartRepoUrl>https://helmcharts.device-insight.com</chartRepoUrl>
        <helmVersion>2.8.2</helmVersion>
      </configuration>
      <executions>
        <execution>
          <goals>
            <goal>helm-package</goal>
            <goal>helm-deploy</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>

....

In the same Maven module, put your helm charts into
`src/main/helm/<chartName>`. In the `Chart.yaml`, you can
use the `${artifactId}` and `${project.version}` Maven placeholders. You can also use Maven properties.

An example for a `Chart.yaml` is:

....
apiVersion: v1
description: A Helm chart installing Rubicon
name: ${artifactId}
version: ${project.version}
home: https://gitlab.device-insight.com/deviceinsight/rubicon
maintainers:
  - name: Device Insight
    url: https://www.device-insight.com
....

You probably also will adjust the `templates/deployment.yaml` so
that the correct docker image is used. An example snippet:

....
[...]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/rubicon:${project.version}"

[...]
....

== Configuration

|===
|Property |Default |Description

|chartName |The Maven `artifactId` |The name of the chart
|chartRepoUrl |None |The URL of the Chart Museum where charts should be published to
|chartRepoUsername |None |The username for basic authentication against the chart repo
|chartRepoPassword |None |The password for basic authentication against the chart repo
|chartFolder |"src/main/helm/<chartName>" |The location of the
chart files (e.g. Chart.yaml).
|skipSnapshots |true |If true, SNAPSHOT versions will be built, but not deployed.
|helmGroupId |`"org.kubernetes.helm"` |The helm binary `groupId`
|helmArtifactId |`"helm-binary"` |The helm binary `artifactId`
|helmVersion |None |The helm binary `version`
|helm.skip |false |If true, execution will be skipped entirely

|===

== Changelog

* 1.17: Set helm chart version via `--version`. This allows to entirely omit the version in the `Chart.yaml`.
  (https://jira.device-insight.com/browse/NGINFRA-142[NGINFRA-142])
* 1.16: Resolve helm binary as a regular Maven artifact. This allows to share the binary via the local Maven repository,
  so it doesn't have to be re-downloaded for every project.
+
WARNING: The properties `helmBinary` and `helmBinaryFetchUrl` were removed. `helmVersion` must be defined instead.

* 1.15: Simplify goal names. Goals now can be run using short names
  (`mvn helm:package helm:deploy`).

* 1.14: Do not create files in the temporary system folder any more

* 1.13: Introduced `helm.skip` property for skipping plugin execution.

* 1.12: Packaging and deploying have been split, so you have
  to add `<goal>helm-deploy</goal>` to the `<goals>` section
  of the configuration. Also, the `<skipPublishing>` option
  has been removed, since the same result can be achieved
  by omitting the `helm-deploy` goal from the `<goals>`.

= Releasing

Creating a new release involves the following steps:

. `mvn -DenableSshAgent=true jgitflow:release-start jgitflow:release-finish` +
[NOTE]
The `-DenableSshAgent=true` is only necessary, if you cloned the repository via SSH.
. `git push origin master`
. `git push --tags`
. `git push origin develop`

