= Usage

Add the following to your `pom.xml`

....
<build>
  <plugins>
    ...
    <plugin>
      <groupId>com.deviceinsight.helm</groupId>
      <artifactId>helm-deploy-maven-plugin</artifactId>
      <version>1.9</version>
      <configuration>
        <chartName>sth-project</chartName>
        <chartRepoUrl>https://helmcharts.device-insight.com</chartRepoUrl>
      </configuration>
      <executions>
        <execution>
          <goals>
            <goal>helm-package</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>

....

In the same Maven module, put your helm charts into
`src/main/helm/<chartName>`. In the `Chart.yaml`, you can
use the `${artifactId}` and `${project.version}` Maven placeholders. You can also use Maven properties.

An example for a `Chart.yaml` is:

....
apiVersion: v1
description: A Helm chart installing Rubicon
name: ${artifactId}
version: ${project.version}
home: https://gitlab.device-insight.com/deviceinsight/rubicon
maintainers:
  - name: Device Insight
    url: https://www.device-insight.com
....

You probably also will adjust the `templates/deployment.yaml` so
that the correct docker image is used. An example snippet:

....
[...]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/rubicon:${project.version}"

[...]
....

== Configuration

|===
|Property |Default |Description

|chartName |The Maven `artifactId` |The name of the chart
|chartRepoUrl |None |The URL of the Chart Museum where charts should be published to
|chartRepoUsername |None |The username for basic authentication against the chart repo
|chartRepoPassword |None |The password for basic authentication against the chart repo
|helmBinary |"helm" |The helm binary to execute. By default assumes that helm is on the path.
|helmBinaryFetchUrl |None |Alternatively to specifying a local helm binary via the 'helmBinary' property. Note, that you cannot specify both 'helmBinary' and 'helmBinaryFetchUrl'

|===

= Releasing

Creating a new release involves the following steps:

. `mvn -DenableSshAgent=true jgitflow:release-start jgitflow:release-finish` +
[NOTE]
The `-DenableSshAgent=true` is only necessary, if you cloned the repository via SSH.
. `git push origin master`
. `git push --tags`
. `git push origin develop`

