= Helm Maven Plugin

== Usage

Add the following to your `pom.xml`

[source,xml]
....
<build>
  <plugins>
    ...
    <plugin>
      <groupId>com.deviceinsight.helm</groupId>
      <artifactId>helm-maven-plugin</artifactId>
      <version>2.0.0</version>
      <configuration>
        <chartName>my-chart</chartName>
        <chartRepoUrl>https://helmcharts.device-insight.com</chartRepoUrl>
        <helmVersion>2.12.1</helmVersion>
      </configuration>
      <executions>
        <execution>
          <goals>
            <goal>package</goal>
            <goal>deploy</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
....

In the same Maven module, put your helm charts into `src/main/helm/<chartName>`. In the `Chart.yaml`, you can use the
`${artifactId}` and `${project.version}` Maven placeholders. You can also use Maven properties.

An example for a `Chart.yaml` is:

[source,yaml]
....
apiVersion: v1
description: A Helm chart installing Rubicon
name: ${artifactId}
version: ${project.version}
home: https://gitlab.device-insight.com/deviceinsight/rubicon
maintainers:
  - name: Device Insight
    url: https://www.device-insight.com
....

You probably also will adjust the `templates/deployment.yaml` so
that the correct docker image is used. An example snippet:

[source,yaml]
....
[...]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/rubicon:${project.version}"
[...]
....

== Configuration

|===
|Property |Default |Description

|chartName |The Maven `artifactId` |The name of the chart
|chartRepoUrl |None |The URL of the Chart Museum where charts should be published to
|chartRepoUsername |None |The username for basic authentication against the chart repo
|chartRepoPassword |None |The password for basic authentication against the chart repo
|chartFolder |`"src/main/helm/<chartName>"` |The location of the chart files (e.g. Chart.yaml).
|skipSnapshots |`true` |If true, SNAPSHOT versions will be built, but not deployed.
|helmGroupId |`"com.deviceinsight.helm"` |The helm binary `groupId`
|helmArtifactId |`"helm"` |The helm binary `artifactId`
|helmVersion |None |The helm binary `version`
|helm.skip |`false` |If true, execution will be skipped entirely

|===

== Releasing

Creating a new release involves the following steps:

. `./mvnw -DenableSshAgent=true jgitflow:release-start jgitflow:release-finish` +
[NOTE]
The `-DenableSshAgent=true` is only necessary, if you cloned the repository via SSH.
. `git push origin master`
. `git push --tags`
. `git push origin develop`

In order to deploy the release to Maven Central, you need to create an account at https://issues.sonatype.org and
configure your account in `~/.m2/settings.xml`:

[source,xml]
....
<settings>
  <servers>
    <server>
      <id>ossrh</id>
      <username>your-jira-id</username>
      <password>your-jira-pwd</password>
    </server>
  </servers>
</settings>
....

The account also needs access to the project on Maven Central. This can be requested by another project member.

Then check out the release you want to deploy (`git checkout x.y.z`) and run `./mvnw deploy -Prelease`.
